name: capacity_metrics_viz
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - streamlit
  - pandas
  - numpy
  - plotly
  - seaborn
  - matplotlib
  - scikit-learn
  - pip
  - pip:
    - streamlit-plotly-events
    - streamlit-aggrid
    - plotly-express 